apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats-demo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cats-demo
  template:
    metadata:
      labels:
        app: cats-demo
    spec:
      containers:
        - name: cats
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP